"""init

Revision ID: 77cd704e00e6
Revises: 
Create Date: 2026-04-29 15:33:56.533886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77cd704e00e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('primary_url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('primary_domain', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('legal_name', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_count', sa.Integer(), nullable=False),
    sa.Column('last_page_crawl_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('normalized_url')
    )
    op.create_index(op.f('ix_companies_primary_domain'), 'companies', ['primary_domain'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('clerk_user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('analysis_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('run_type', sa.Text(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('force_refresh', sa.Boolean(), nullable=False),
    sa.Column('input_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('collection_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('parent_run_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['analysis_runs.run_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_analysis_runs_requested_by_user_id'), 'analysis_runs', ['requested_by_user_id'], unique=False)
    op.create_table('comparison_sessions',
    sa.Column('comparison_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('comparison_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_model', sa.Text(), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('share_id', sa.Text(), nullable=True),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('comparison_id'),
    sa.UniqueConstraint('share_id')
    )
    op.create_index(op.f('ix_comparison_sessions_created_by_user_id'), 'comparison_sessions', ['created_by_user_id'], unique=False)
    op.create_table('pages',
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('page_type', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_content_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id'),
    sa.UniqueConstraint('company_id', 'normalized_url', name='uq_pages_company_url')
    )
    op.create_index(op.f('ix_pages_company_id'), 'pages', ['company_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('llm_model', sa.Text(), nullable=False),
    sa.Column('llm_api_version', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('structured', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diff_report', sa.Text(), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('markdown_page', sa.Text(), nullable=True),
    sa.Column('pages_used', sa.Integer(), nullable=False),
    sa.Column('quality_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('share_id', sa.Text(), nullable=True),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.run_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('result_id'),
    sa.UniqueConstraint('run_id'),
    sa.UniqueConstraint('share_id')
    )
    op.create_table('page_versions',
    sa.Column('page_version_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('fetch_run_id', sa.UUID(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('lang', sa.Text(), nullable=True),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('page_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetch_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fetch_run_id'], ['analysis_runs.run_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.page_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_version_id')
    )
    op.create_index(op.f('ix_page_versions_content_hash'), 'page_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_page_versions_fetch_run_id'), 'page_versions', ['fetch_run_id'], unique=False)
    op.create_index(op.f('ix_page_versions_page_id'), 'page_versions', ['page_id'], unique=False)
    op.create_table('analysis_result_sources',
    sa.Column('analysis_result_source_id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('page_version_id', sa.UUID(), nullable=False),
    sa.Column('source_order', sa.Integer(), nullable=False),
    sa.Column('page_category', sa.Text(), nullable=True),
    sa.Column('citation_title', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('citation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_version_id'], ['page_versions.page_version_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_id'], ['analysis_results.result_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_result_source_id')
    )
    op.create_table('comparison_session_items',
    sa.Column('comparison_item_id', sa.UUID(), nullable=False),
    sa.Column('comparison_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparison_sessions.comparison_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_id'], ['analysis_results.result_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('comparison_item_id')
    )
    op.create_table('deep_research_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('base_result_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('retrieval_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_result_id'], ['analysis_results.result_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_deep_research_sessions_created_by_user_id'), 'deep_research_sessions', ['created_by_user_id'], unique=False)
    op.create_table('deep_research_messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieval_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('additional_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['deep_research_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deep_research_messages')
    op.drop_index(op.f('ix_deep_research_sessions_created_by_user_id'), table_name='deep_research_sessions')
    op.drop_table('deep_research_sessions')
    op.drop_table('comparison_session_items')
    op.drop_table('analysis_result_sources')
    op.drop_index(op.f('ix_page_versions_page_id'), table_name='page_versions')
    op.drop_index(op.f('ix_page_versions_fetch_run_id'), table_name='page_versions')
    op.drop_index(op.f('ix_page_versions_content_hash'), table_name='page_versions')
    op.drop_table('page_versions')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_pages_company_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_comparison_sessions_created_by_user_id'), table_name='comparison_sessions')
    op.drop_table('comparison_sessions')
    op.drop_index(op.f('ix_analysis_runs_requested_by_user_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_primary_domain'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
