"""add_page_snapshots_deep_research_comparison

Revision ID: cf968a334637
Revises: 02f6f6aa81dc
Create Date: 2026-04-27 18:12:10.776916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf968a334637'
down_revision: Union[str, Sequence[str], None] = '02f6f6aa81dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparison_sessions',
    sa.Column('comparison_id', sa.UUID(), nullable=False),
    sa.Column('company_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('result_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('comparison_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('share_id', sa.Text(), nullable=True),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('llm_model', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('comparison_id'),
    sa.UniqueConstraint('share_id')
    )
    op.create_table('page_snapshots',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('og_title', sa.Text(), nullable=True),
    sa.Column('og_description', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('lang', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetch_duration_ms', sa.Integer(), nullable=True),
    sa.Column('is_changed', sa.Boolean(), nullable=False),
    sa.Column('previous_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('company_id', 'normalized_url', name='uq_page_snapshots_company_url')
    )
    op.create_table('deep_research_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('additional_pages_fetched', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_id'], ['analysis_results.result_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('deep_research_messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('used_cached_data', sa.Boolean(), nullable=True),
    sa.Column('additional_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['deep_research_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deep_research_messages')
    op.drop_table('deep_research_sessions')
    op.drop_table('page_snapshots')
    op.drop_table('comparison_sessions')
    # ### end Alembic commands ###
